---
- name: Install mutt
  apt: pkg=mutt state=present
  become: true

- name: Configure .muttrc file
  template:
    src: muttconfig.jinja2
    dest: /home/{{ mg_user }}/.muttrc
    owner: "{{ mg_user }}"
    mode: 0600
