---
- name: Install mutt
  apt: name=mutt state=present
  when: ansible_os_family == "Debian"
  become: true

- name: Install mutt
  pkgng: name=mutt state=present
  when: ansible_os_family == "FreeBSD"
  become: true

- name: Configure .muttrc file
  template:
    src: muttconfig.jinja2
    dest: /home/{{ mg_user }}/.muttrc
    owner: "{{ mg_user }}"
    mode: 0600
